{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tito-ms-productos-postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
{{- end }}