{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tito-ms-productos-postgres
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: tito-ms-productos-postgres
  ports:
    - name: tcp-postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
{{- end }}