app:
  image:
    repository: "jose196/tito-gateway"
    tag: "v1.0"
    pullPolicy: "Always"
  containerPort: 3000


service:
  type: NodePort
  port: 3000
  nodePort: 30080


ingress:
  enabled: true
  className: nginx
  host: api.jrodrodriguez.es
  path: /
  pathType: Prefix