{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tito-ms-gateway
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  ports:
    - port: {{ .Values.service.port | default 3000 }}
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort | default 30080 }}
      protocol: TCP
      name: http
  selector:
    app: tito-ms-gateway # Debe coincidir exactamente con el label del Deployment
{{- end }}