{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tito-ms-usuarios-postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  # Se toma la contrase√±a del archivo values.yaml
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
{{- end }}