{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tito-ms-usuarios-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP # Interno del cl√∫ster
  selector:
    app: tito-ms-usuarios # Debe coincidir exactamente con las labels del Deployment
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.containerPort }}
{{- end }}