version: '3'

services:
  # --- BASE DE DATOS (EXCLUSIVA PARA PRODUCTOS) ---
  db-products:
    image: postgres:15 # Usamos la versión 15 de PostgreSQL
    container_name: postgres-products # Nombre del contenedor de la BD
    restart: always # Si se cae, intenta levantarse sola
    environment:
      # Credenciales para entrar a la base de datos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_products # Nombre de la base de datos interna
    ports:
      # Tu ordenador (5434) <-> Contenedor (5432).
      # Usamos el 5434 para que no choque con la BD de usuarios.
      - "5434:5432"
    volumes:
      # Guarda los datos en una carpeta 'data/products' de tu proyecto
      # para no perderlos si borras el contenedor.
      - ./data/products:/var/lib/postgresql/data
    networks:
      - tito-network # Se conecta a la red compartida

  # --- MICROSERVICIO (TU CÓDIGO) ---
  ms-productos:
    build:
      context: ../../../ # Sube 3 niveles para ver todo el proyecto
      dockerfile: ./apps/ms-productos/deploy/Dockerfile # La receta de instalación
      args:
        - MICROSERVICIO=ms-productos # Le dice qué carpeta compilar
    container_name: tito-ms-productos
    ports:
      - "3002:3002" # Accesible en localhost:3002
    env_file:
      - .env # Carga las contraseñas y configuración del archivo .env
    environment:
      # ¡IMPORTANTE! Aquí le decimos cómo conectar con SU base de datos.
      # Fíjate que usa 'postgres-products' (el nombre del contenedor de arriba) como dirección.
      DATABASE_URL: postgres://admin:admin@postgres-products:5432/db_products
      MS_PRODUCTS_PORT: 3002
      NODE_ENV: development
      NATS_SERVERS: "nats://nats-server1:4222"
    depends_on:
      - db-products # Espera a que la BD arranque antes de iniciarse él
    networks:
      - tito-network

# Configuración extra (volúmenes y redes)
volumes:
  postgres_data:

networks:
  tito-network:
    external: true # Usa la red que creamos manualmente al principio