db-products:
    image: postgres:15
    container_name: postgres-products
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_products
    ports:
      - "5434:5432"
    volumes:
      - ./data/products:/var/lib/postgresql/data
