{{- if .Values.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  labels:
    app: nats
spec:
  serviceName: nats
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if .Values.jetstream.enabled }}
            - "-js"
            {{- end }}
            - "-m"
            - "{{ .Values.ports.monitoring }}"
          ports:
            - name: client
              containerPort: {{ .Values.ports.client }}
            - name: monitoring
              containerPort: {{ .Values.ports.monitoring }}
            - name: cluster
              containerPort: {{ .Values.ports.cluster }}
          volumeMounts:
            - name: nats-data
              mountPath: /data
  volumeClaimTemplates:
    {{- if .Values.persistence.enabled }}
    - metadata:
        name: nats-data
      spec:
        accessModes: {{ toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
    {{- end }}
{{- end }}