apiVersion: v2
name: jenkins-config  # <--- CAMBIA ESTO (Antes era 'jenkins')
description: Jenkins CI
type: application
version: 0.1.0

dependencies:
  - name: jenkins     # <--- Deja esto como estÃ¡
    version: 5.8.7
    repository: https://charts.jenkins.io