enabled: true

app:
  image:
    repository: "jose196/tito-gateway"
    tag: "v1.2"
    pullPolicy: Always
  containerPort: 3002   
  container: 
    name: tito-ms-productos
    replicas: 1

service:
  type: ClusterIP
  port: 3002

postgres:
  name: tito-ms-productos-postgres
  image:
    repository: postgres
    tag: "15-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  auth:
    database: bdproductos
    username: admin
    password: admin_productos_pass
  persistence:
    enabled: true
    size: 2Gi
    storageClassName: "microk8s-hostpath"

env:
  NODE_ENV: "production"
  DATABASE_HOST: "tito-ms-productos-postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "bdproductos"
  DATABASE_USER: "admin"

global:
  env:
    PORT: "3002"
    REPO_GIT: "git@github.com:Rodriguez-22/backend-mc-pnpm.git"