enabled: true

app:
  image:
    repository: "jose196/tito-gateway" # Usas la misma imagen que contiene todo el repo
    tag: "v1.2"
    pullPolicy: Always
  containerPort: 3002
  container: 
    name: tito-ms-productos
    replicas: 1

service:
  type: ClusterIP
  port: 3002

postgres:
  name: tito-ms-productos-postgres
  image:
    repository: postgres
    tag: "15-alpine"
  service:
    port: 5432
  auth:
    database: bdproductos
    username: admin
    password: admin_productos_pass
  persistence:
    enabled: true
    size: 2Gi
    storageClassName: "hostpath"

global:
  env:
    PORT: "3002"
    REPO_GIT: "git@github.com:Rodriguez-22/backend-mc-pnpm.git"