services:
  # Base de datos para Users
  db-users:
    image: postgres:15
    container_name: postgres-users
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_users
    ports:
      - "5432:5432"
    volumes:
      - ./data/users:/var/lib/postgresql/data