services:
  postgresUsuarios:
    image: postgres:15-alpine
    container_name: backend-mc-pnpm
    env_file:
      - .env
    environment:
      CONTEXT: /Jose/devops/DespAW/docker
      #POSTGRES_HOST:
      #POSTGRES_PORT:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - backend-mc-pnpm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  # Base de datos para Users
  ms-usuarios:
    profiles: ["usuarios"]
    build:
      context: ${CONTEXTO}
      dockerfile: ./apps/${MICROSERVICIO}/deploy/Dockerfile
      args:
        - CONTEXT=${CONTEXTO}
        - MICROSERVICIO=${MICROSERVICIO}
    container_name: backend-mc-users
    # restart: unless-stopped
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV: production
    networks:
      - backend-mc-pnpm-network
    # healthcheck:
    #   test: ["CMD", "node", "-e", "require('net').connect(3001)"]
    #   interval: 10s
    #   timeout: 50s
    #   retries: 5


volumes:
  postgres_data:

networks:
  backend-mc-pnpm-network:
    driver: bridge