# {{- if .Values.enabled }}
# apiVersion: v1
# kind: Service
# metadata:
#   name: tito-ms-gateway-service
#   namespace: {{ .Release.Namespace }}
# spec:
#   type: {{ .Values.service.type }}
#   selector:
#     app: tito-ms-gateway
#   ports:
#     - name: http
#       port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#   selector:
#     app.kubernetes.io/name: {{ include "ms-gateway.name" . }}
# {{- end }}